In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
CC = pd.read_excel('C:/Users/Aarons/Documents/pandas_to_excel.xlsx')
CC.head()

,Unnamed: 0,Cancer_id,Name,Category,State_name,Race_name,Count,Percentage population below poverty,Percentage population insured,Population
0,66,27060,Vulva,Female Genital System,Arkansas,Asian or Pacific Islander,0,18.8,90.6,3004279
1,621,27020,Corpus Uteri,Female Genital System,New Jersey,Black or African American,221,10.9,90.8,9005644
2,780,27070,Other Female Genital Organs,Female Genital System,Oregon,Black or African American,0,15.7,92.6,4142776
3,990,27030,"Uterus, NOS",Female Genital System,Washington,Other Races and Unknown combined,0,12.7,93.1,7405743
4,446,27050,Vagina,Female Genital System,Massachusetts,American Indian or Alaska Native,0,11.4,97.0,6859819

In [3]:
PovertyRate = pd.read_excel('C:/Users/Aarons/Documents/data-PAwRQ.xlsx')
PovertyRate.head()

,State,Poverty Rank,2019 Percent of population living below poverty level,2014 Percent of population living below poverty level,5-Year Change
0,Alabama,44,16.7%,18.9%,-2.2%
1,Alaska,11,10.7%,10.1%,0.6%
2,Arizona,39,15.1%,18.2%,-3.1%
3,Arkansas,45,17.0%,19.2%,-2.2%
4,California,30,13.4%,16.4%,-3.0%

In [4]:
CC.rename(columns={'State_name': 'State', 'Percentage_population_below_poverty': 'Poverty%', 'Race_name': 'Race', 'Percentage population insured': 'Insured'}, inplace=True)

In [5]:
PovertyCancer = pd.merge(CC, PovertyRate, on='State')

In [7]:
PC = PovertyCancer.rename(columns={'2019 Percent of population living below poverty level': '2019Poverty%', '2014 Percent of population living below poverty level': '2014Poverty%', 'Percentage population below poverty': 'Poverty%'}, inplace=True)

In [9]:
PovertyCancer.head()

,Unnamed: 0,Cancer_id,Name,Category,State,Race,Count,Poverty%,Insured,Population,Poverty Rank,2019Poverty%,2014Poverty%,5-Year Change
0,66,27060,Vulva,Female Genital System,Arkansas,Asian or Pacific Islander,0,18.8,90.6,3004279,45,17.0%,19.2%,-2.2%
1,63,27050,Vagina,Female Genital System,Arkansas,American Indian or Alaska Native,0,18.8,90.6,3004279,45,17.0%,19.2%,-2.2%
2,58,27020,Corpus Uteri,Female Genital System,Arkansas,Black or African American,49,18.8,90.6,3004279,45,17.0%,19.2%,-2.2%
3,70,27070,Other Female Genital Organs,Female Genital System,Arkansas,Asian or Pacific Islander,0,18.8,90.6,3004279,45,17.0%,19.2%,-2.2%
4,65,27060,Vulva,Female Genital System,Arkansas,American Indian or Alaska Native,0,18.8,90.6,3004279,45,17.0%,19.2%,-2.2%

In [10]:
PovertyCancer = PovertyCancer.drop(['Cancer_id', '5-Year Change', 'Unnamed: 0', 'Category'], axis = 1)
PovertyCancer.head()

,Name,State,Race,Count,Poverty%,Insured,Population,Poverty Rank,2019Poverty%,2014Poverty%
0,Vulva,Arkansas,Asian or Pacific Islander,0,18.8,90.6,3004279,45,17.0%,19.2%
1,Vagina,Arkansas,American Indian or Alaska Native,0,18.8,90.6,3004279,45,17.0%,19.2%
2,Corpus Uteri,Arkansas,Black or African American,49,18.8,90.6,3004279,45,17.0%,19.2%
3,Other Female Genital Organs,Arkansas,Asian or Pacific Islander,0,18.8,90.6,3004279,45,17.0%,19.2%
4,Vulva,Arkansas,American Indian or Alaska Native,0,18.8,90.6,3004279,45,17.0%,19.2%

In [12]:
PvsC1 = PovertyCancer[PovertyCancer['Poverty Rank'] >= 41]

In [19]:
PvsC1.head()

,Name,State,Race,Count,Poverty%,Insured,Population,Poverty Rank,2019Poverty%,2014Poverty%
0,Vulva,Arkansas,Asian or Pacific Islander,0,18.8,90.6,3004279,45,17.0%,19.2%
1,Vagina,Arkansas,American Indian or Alaska Native,0,18.8,90.6,3004279,45,17.0%,19.2%
2,Corpus Uteri,Arkansas,Black or African American,49,18.8,90.6,3004279,45,17.0%,19.2%
3,Other Female Genital Organs,Arkansas,Asian or Pacific Islander,0,18.8,90.6,3004279,45,17.0%,19.2%
4,Vulva,Arkansas,American Indian or Alaska Native,0,18.8,90.6,3004279,45,17.0%,19.2%

In [15]:
PvsC2 = PovertyCancer[PovertyCancer['Poverty Rank'] <= 10]

In [20]:
PvsC2.head()

,Name,State,Race,Count,Poverty%,Insured,Population,Poverty Rank,2019Poverty%,2014Poverty%
16,Corpus Uteri,New Jersey,Black or African American,221,10.9,90.8,9005644,7,10.0%,10.7%
17,Ovary,New Jersey,American Indian or Alaska Native,0,10.9,90.8,9005644,7,10.0%,10.7%
18,Ovary,New Jersey,Asian or Pacific Islander,64,10.9,90.8,9005644,7,10.0%,10.7%
19,"Uterus, NOS",New Jersey,Black or African American,23,10.9,90.8,9005644,7,10.0%,10.7%
20,Cervix Uteri,New Jersey,Asian or Pacific Islander,27,10.9,90.8,9005644,7,10.0%,10.7%

In [21]:
PvsC1.State.unique()

array(['Arkansas', 'South Carolina', 'West Virginia', 'Mississippi',
       'New Mexico', 'Oklahoma', 'Louisiana', 'Kentucky', 'Tennessee',
       'Alabama'], dtype=object)

In [22]:
PvsC2.State.unique()

array(['New Jersey', 'Massachusetts', 'Utah', 'New Hampshire', 'Colorado',
       'Hawaii', 'Maryland', 'Virginia', 'Minnesota', 'Connecticut'],
      dtype=object)

In [23]:
print (PvsC1)

                            Name     State                              Race  \
0                          Vulva  Arkansas         Asian or Pacific Islander
1                         Vagina  Arkansas  American Indian or Alaska Native
2                   Corpus Uteri  Arkansas         Black or African American
3    Other Female Genital Organs  Arkansas         Asian or Pacific Islander
4                          Vulva  Arkansas  American Indian or Alaska Native
..                           ...       ...                               ...
964                        Ovary   Alabama         Black or African American
965                 Corpus Uteri   Alabama                             White
966                 Cervix Uteri   Alabama                             White
967                        Vulva   Alabama                             White
968                        Ovary   Alabama                             White

     Count  Poverty%  Insured  Population  Poverty Rank 2019Poverty%  \
0        0      18.8     90.6     3004279            45        17.0%
1        0      18.8     90.6     3004279            45        17.0%
2       49      18.8     90.6     3004279            45        17.0%
3        0      18.8     90.6     3004279            45        17.0%
4        0      18.8     90.6     3004279            45        17.0%
..     ...       ...      ...         ...           ...          ...
964     71      18.4     89.2     4874747            44        16.7%
965    447      18.4     89.2     4874747            44        16.7%
966    152      18.4     89.2     4874747            44        16.7%
967     71      18.4     89.2     4874747            44        16.7%
968    268      18.4     89.2     4874747            44        16.7%

    2014Poverty%
0          19.2%
1          19.2%
2          19.2%
3          19.2%
4          19.2%
..           ...
964        18.9%
965        18.9%
966        18.9%
967        18.9%
968        18.9%

[192 rows x 10 columns]

In [24]:
PvsC1.to_excel (r'C:/Users/Aarons/Documents/PvsC1.xlsx', index = False, header=True)

In [25]:
PvsC1.to_csv (r'C:/Users/Aarons/Documents/PvsC1.csv', index = False, header=True)

In [26]:
print (PvsC2)

                            Name        State  \
16                  Corpus Uteri   New Jersey
17                         Ovary   New Jersey
18                         Ovary   New Jersey
19                   Uterus, NOS   New Jersey
20                  Cervix Uteri   New Jersey
..                           ...          ...
984  Other Female Genital Organs  Connecticut
985                 Corpus Uteri  Connecticut
986                  Uterus, NOS  Connecticut
987                        Vulva  Connecticut
988                 Cervix Uteri  Connecticut

                                 Race  Count  Poverty%  Insured  Population  \
16          Black or African American    221      10.9     90.8     9005644
17   American Indian or Alaska Native      0      10.9     90.8     9005644
18          Asian or Pacific Islander     64      10.9     90.8     9005644
19          Black or African American     23      10.9     90.8     9005644
20          Asian or Pacific Islander     27      10.9     90.8     9005644
..                                ...    ...       ...      ...         ...
984                             White     23      10.4     94.2     3588184
985                             White    604      10.4     94.2     3588184
986                             White     19      10.4     94.2     3588184
987                             White     57      10.4     94.2     3588184
988                             White     98      10.4     94.2     3588184

     Poverty Rank 2019Poverty% 2014Poverty%
16              7        10.0%        10.7%
17              7        10.0%        10.7%
18              7        10.0%        10.7%
19              7        10.0%        10.7%
20              7        10.0%        10.7%
..            ...          ...          ...
984             6         9.9%        10.5%
985             6         9.9%        10.5%
986             6         9.9%        10.5%
987             6         9.9%        10.5%
988             6         9.9%        10.5%

[200 rows x 10 columns]

In [27]:
PvsC2.to_excel (r'C:/Users/Aarons/Documents/PvsC2.xlsx', index = False, header=True)

In [28]:
PvsC2.to_csv (r'C:/Users/Aarons/Documents/PvsC2.csv', index = False, header=True)